---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-cert-adminbot
  namespace: {{ .Release.Name }}-management
  labels:
    app.kubernetes.io/name: kube-ctf
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  secretName: {{ .Release.Name }}-cert-adminbot
  issuerRef:
    kind: ClusterIssuer
    name: {{ .Release.Name }}-letsencrypt
  dnsNames:
  - {{ .Values.domain.adminbot }}
  - "*.{{ .Values.domain.adminbot }}"